# Copyright (C) 2015  Stephan Kreutzer
#
# This file is part of vpl2haggai1.
#
# vpl2haggai1 is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3 or any later version,
# as published by the Free Software Foundation.
#
# vpl2haggai1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License 3
# along with vpl2haggai1. If not, see <http://www.gnu.org/licenses/>.



.PHONY: all vpl2haggai1 clean



all: vpl2haggai1
vpl2haggai1: vpl2haggai1.class



vpl2haggai1.class: vpl2haggai1.java
	javac vpl2haggai1.java

clean:
	rm -f ./vpl2haggai1.class
	rm -f ./BibleBookInfo.class



